### ISSUE TITLE
Installation manual: Vagrant needs vagrant-hostmanager

### ISSUE THREAD

**Issue by rstribrn** [vtorosyan/ansible-docker-vagrant-example#1]
Installation manual is missing information that vagrant "vagrant-hostmanager" plugin is required:

vagrant plugin install vagrant-hostmanager

**Comment by vtorosyan** [comment]
Thanks for the issue, here is the [fix](https://github.com/vtorosyan/vtorosyan.github.io/commit/1f099215d67dcb5a5bbca46c36cd892b38eaed78)
